name: jelajahin_apps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.7
  image_picker: ^1.1.1
  uuid: ^4.3.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.4.0
  flutter_map_cancellable_tile_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/